version: '3.8'

services:
  sso:
    container_name: sso
    command: sh -c "/app/migrator & /app/sso wait"
    depends_on:
     - sso-db
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CONFIG_PATH=./config/local.yaml
    volumes:
      - ./config:/app/config:ro
      - ./migrations:/app/migrations:ro
    networks:
      - sso_net
    ports:
      - 44043:44043

  sso-db:
    image: postgres:15
    container_name: sso-db
    env_file:
     - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sso_net
volumes:
  postgres_data:
networks:
  sso_net: